server:
    port: 8000
spring:
    devtools:
        livereload:
            enabled: true
    datasource:
        url: jdbc:mysql://localhost:3306/rollin?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 123123123
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 10MB
mybatis:
    config-location: classpath:config/MyBatis.xml
